#!/bin/bash
export SERVER_IP_ADDRESS="${1}"
export KIOSK_IMAGE_ID="${2}"
export LOCAL_MACHINE="${3}"
export KIOSK_APP_NAME="${4}"
export CUSTOM_SCRIPTS_TO_RUN="${5}"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts
export HOME=/root
export LC_ALL=C
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl
cp -r /workspace/kiosk-worker /usr/local/kiosk-worker

#running commands for kiosk-image creation from empty ubuntu
chmod +x /workspace/prepare_kiosk
. /workspace/prepare_kiosk

apt clean
rm -rf /tmp/* ~/.bash_history
rm /etc/resolv.conf
rm /var/lib/dbus/machine-id
rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl
umount /proc || umount -lf /proc
umount /sys
umount /dev/pts
umount /dev
umount /run
exit 0