#!/bin/sh
#Script is made from documentation https://help.ubuntu.com/community/LiveCDCustomization
echo "create custom image" && \
BASE_IMAGE_NAME=$1 &&\
IMAGE_NAME=Kiosk &&\
sudo apt install -y squashfs-tools genisoimage &&\
mkdir build &&\
cd build &&\
mkdir -p mnt &&\
mkdir -p extract-cd &&\
scp ../images/${BASE_IMAGE_NAME} . &&\
sudo mount -o loop ${BASE_IMAGE_NAME} mnt &&\
sudo rsync --exclude=/casper/filesystem.squashfs -a mnt/ extract-cd &&\
sudo unsquashfs mnt/casper/filesystem.squashfs &&\
sudo mv squashfs-root edit &&\
sudo cp /etc/resolv.conf edit/etc/ &&\
sudo mount -o bind /run/ edit/run &&\
sudo mount --bind /dev/ edit/dev &&\
sudo mkdir edit/workspace &&\
scp ../prepare_kiosk edit/workspace &&\
scp ../chroot_commands edit/workspace &&\
sudo chmod +w extract-cd/casper/filesystem.manifest &&\
sudo chroot edit /workspace/chroot_commands &&\
echo Producing the CD image &&\

#sudo su &&\
#sudo chroot edit dpkg-query -W --showformat='${Package} ${Version}\n' > extract-cd/casper/filesystem.manifest &&\
#exit &&\
sudo cp extract-cd/casper/filesystem.manifest extract-cd/casper/filesystem.manifest-desktop &&\
sudo sed -i '/ubiquity/d' extract-cd/casper/filesystem.manifest-desktop &&\
sudo sed -i '/casper/d' extract-cd/casper/filesystem.manifest-desktop &&\
echo Compression &&\
sudo mksquashfs edit extract-cd/casper/filesystem.squashfs -b 1048576 &&\
printf $(du -sx --block-size=1 edit | cut -f1) > extract-cd/casper/filesystem.size &&\
echo old md5sum.txt and calculate new md5 sums &&\
cd extract-cd &&\
sudo rm md5sum.txt &&\
find -type f -print0 | sudo xargs -0 md5sum | grep -v isolinux/boot.cat | sudo tee md5sum.txt &&\
echo the ISO image &&\
sudo mkisofs -D -r -V "$IMAGE_NAME" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../ubuntu-20.04.2-server-custom.iso . &&\
cd ..
umount mnt &&\
rm -r mnt &&\
rm -rf edit &&\
rm -rf extract-cd &&\
rm -rf workspace &&\
rm -rf $BASE_IMAGE_NAME