#!/bin/bash
sudo apt update && \
sudo apt upgrade -y && \
sudo apt install -y libegl1-mesa libegl1 && \
sudo apt install -y xwayland && \
sudo apt install -y xdotool && \
sudo apt install -y mingetty && \
sudo apt install -y scrot && \
sudo apt install -y sed && \
sudo apt install -y python3-pip && \
sudo pip install requests && \
sudo pip install Flask && \
${CUSTOM_SCRIPTS_TO_RUN} && \
sudo mkdir /etc/systemd/system/getty@tty1.service.d && \
sudo useradd -m -G sudo --shell /bin/bash kiosk && \
sudo passwd kiosk<<EOF
z13z/Kiosk
z13z/Kiosk
EOF
sudo echo -en "\n\nkiosk ALL=(ALL) NOPASSWD: ALL">>/etc/sudoers && \
sudo cat >/etc/systemd/system/getty@tty1.service.d/override.conf <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty --noissue --autologin kiosk %I \$TERM
Type=idle
EOF
sudo cat >/etc/systemd/system/kiosk.service<<EOF
[Unit]
Description=Mount unit Kiosk
After=snapd.service

[Service]
ExecStart=/usr/local/bin/kiosk.sh
Environment=KIOSK_APP_NAME=APPLICATION_NAME_PLACEHOLDER
User=kiosk
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
EOF
sudo sed -i "s/APPLICATION_NAME_PLACEHOLDER/${KIOSK_APP_NAME}/g" /etc/systemd/system/kiosk.service && \
sudo chmod 664 /etc/systemd/system/kiosk.service && \
sudo cat >/usr/local/bin/kiosk.sh<<EOF
#!/bin/bash
set -m && export XDG_RUNTIME_DIR=/run/user/1000 && sleep 13 && \
(sudo snap get mir-kiosk &>/dev/null || sudo snap install mir-kiosk --devmode) && \
(/snap/bin/mir-kiosk &>/dev/null &) && sleep 8 && export DISPLAY=:1 && \
(Xwayland -wr \$DISPLAY &>/dev/null &) && sleep 8
echo "starting \${KIOSK_APP_NAME}"
(sleep 13 && xdotool windowsize \$(xdotool search --onlyvisible --name \${KIOSK_APP_NAME}) 100% 100%) &
\${KIOSK_APP_NAME}
EOF
sudo chmod 777 /usr/local/bin/kiosk.sh && \
sudo systemctl enable kiosk.service && \
sudo cat >/etc/systemd/system/kiosk_worker.service<<EOF
[Unit]
Description=Mount unit Kiosk
After=snapd.service

[Service]
ExecStart=/usr/local/kiosk-worker/main.py
Environment=KIOSK_SERVER=KIOSK_SERVER_PLACEHOLDER
Environment=KIOSK_IMAGE_ID=KIOSK_IMAGE_ID_PLACEHOLDER
Environment=LOCAL_MACHINE=LOCAL_MACHINE_PLACEHOLDER
User=root
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF
sudo sed -i "s/KIOSK_SERVER_PLACEHOLDER/${SERVER_IP_ADDRESS}/g" /etc/systemd/system/kiosk_worker.service && \
sudo sed -i "s/KIOSK_IMAGE_ID_PLACEHOLDER/${KIOSK_IMAGE_ID}/g" /etc/systemd/system/kiosk_worker.service && \
sudo sed -i "s/LOCAL_MACHINE_PLACEHOLDER/${LOCAL_MACHINE}/g" /etc/systemd/system/kiosk_worker.service && \
sudo chmod 664 /etc/systemd/system/kiosk_worker.service && \
sudo chmod 777 /usr/local/kiosk-worker/main.py && \
sudo systemctl enable kiosk_worker.service

